language: go

go:
  - 1.13.x

services:
  - docker

stages:
  - name: test
    if: tag IS blank
  # - name: deploy
  #   if: 
  #     - tag = latest

jobs:
  include:
    - stage: test
      script:
        - export GO111MODULE=on
        - go mod download
        - go test -v ./...
        - touch .env
        - docker-compose build
    # - stage: deploy
    #   script:
    #     - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
    #     - touch .env
    #     - docker-compose build
    #     - docker-compose push
