version: "3.6"
services:
  elastic:
    environment:
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"

  api:
    volumes:
      - /etc/bcd:/etc/bcd
      - ./cmd/api/config.json:/app/api/config.json

  indexer:
    volumes:
      - /etc/bcd:/etc/bcd
      - ./cmd/indexer/config.json:/app/indexer/config.json

  opindexer:
    volumes:
      - ./cmd/operation_indexer/config.json:/app/operation_indexer/config.json

  metrics:
    volumes:
      - ./cmd/metrics/config.json:/app/metrics/config.json
