share:
    path: ${HOME}/.bcd

sentry:
    environment: development
    uri: ${SENTRY_DSN}
    debug: true

elastic:
    uri: http://127.0.0.1:9200
    timeout: 1

db:
    conn_string: "host=127.0.0.1 port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB} password=${POSTGRES_PASSWORD} sslmode=disable"

oauth:
    state: ${OAUTH_STATE_STRING}
    jwt:
        secret: ${JWT_SECRET_KEY}
        redirect_url: http://localhost:8080/welcome
    github:
        client_id: ${GITHUB_CLIENT_ID}
        secret: ${GITHUB_CLIENT_SECRET}
        callback_url: http://localhost:14000/v1/oauth/github/callback
    gitlab:
        client_id: ${GITLAB_CLIENT_ID}
        secret: ${GITLAB_CLIENT_SECRET}
        callback_url: http://localhost:14000/v1/oauth/gitlab/callback

api:
    bind: "127.0.0.1:14000"
    swagger_host: "localhost:14000"
    oauth:
        enabled: true
    sentry:
        enabled: false
        project: api
    networks:
        - mainnet
        - carthagenet
        - zeronet
        - dalphanet
    seed:
        enabled: false

rabbitmq:
    uri: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@127.0.0.1:5672/"
    queues:
        - operations
        - recalc
