rpc:
    mainnet:
        uri: https://rpc.tzkt.io/mainnet
        timeout: 20
    delphinet:
        uri: https://rpc.tzkt.io/delphinet
        timeout: 20
    dalphanet:
        uri: https://rpc.tzkt.io/dalphanet
        timeout: 20
    carthagenet:
        uri: https://rpc.tzkt.io/carthagenet
        timeout: 20
    sandboxnet:
        uri: http://sandbox:8732
        timeout: 10

tzkt:
    mainnet:
        uri: https://api.tzkt.io/v1/
        timeout: 20
    delphinet:
        uri: https://api.delphinet.tzkt.io/v1/
        timeout: 20
    carthagenet:
        uri: https://api.carthage.tzkt.io/v1/
        timeout: 20

share:
    path: /etc/bcd

elastic:
    uri: http://127.0.0.1:9200
    timeout: 30

rabbitmq:
    uri: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@127.0.0.1:5672/"
    queues:
        - operations
        - contracts
        - migrations
        - recalc

db:
    conn_string: "host=127.0.0.1 port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB} password=${POSTGRES_PASSWORD} sslmode=disable"

aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1

migrations:
    networks:
        - mainnet
        - carthagenet
        - delphinet
        - dalphanet
